export const PermissionResource = {
  USER: 'user',
  ROLE: 'role',
  PERMISSION: 'permission',
  AUDIT_LOG: 'auditLog',
  SYSTEM: 'system',
  APPROVAL: 'approval',
  FILE: 'file',
  JOB: 'job',
  IDENTITY_PROVIDER: 'identityProvider',
  GROUP: 'group',
  SERVICE_ACCOUNT: 'serviceAccount',
  WEBHOOK: 'webhook',
  TAG: 'tag',
  NOTIFICATION: 'notification',
  ANNOUNCEMENT: 'announcement',
  MFA_POLICY: 'mfaPolicy',
  ORG_UNIT: 'orgUnit',
  APPROVAL_FLOW: 'approvalFlow',
} as const;
export type PermissionResource = (typeof PermissionResource)[keyof typeof PermissionResource];
