import type { PermissionKey } from './permissions';

export interface RoleSeed {
  slug: string;
  name: string;
  description: string;
  isSystem: true;
  /** `'*'` 代表隱含全集：只寫租戶節點上的 `superAdmin` 邊，不寫任何權限鍵。 */
  permissions: '*' | readonly PermissionKey[];
}

export const ROLE_SEED: readonly RoleSeed[] = [
  {
    slug: 'super-admin',
    name: '超級管理員',
    description: '系統最高權限，繞過所有權限檢查。不可刪除、不可調整權限。',
    isSystem: true,
    permissions: '*',
  },
  {
    slug: 'admin',
    name: '系統管理員',
    description: '管理使用者、角色與權限。',
    isSystem: true,
    permissions: [
      'user:create',
      'user:read',
      'user:update',
      'user:delete',
      'user:assignRole',
      'user:resetPassword',
      'user:resetMfa',
      'user:export',
      'role:create',
      'role:read',
      'role:update',
      'role:delete',
      'role:grantPermission',
      'role:export',
      'permission:read',
      'auditLog:read',
      'auditLog:export',
      'system:read',
      'approval:read',
      'approval:review',
      'approval:export',
      'file:create',
      'file:read',
      'file:update',
      'file:delete',
      'file:share',
      // member 有 file:access：admin 要持有它才能指派 member（反提權）
      'file:access',
      // 全域 file:read 已經看得到全部；持有它才能把它指派給自訂角色（反提權）
      'file:listPersonal',
      'job:read',
      'job:retry',
      'identityProvider:create',
      'identityProvider:read',
      'identityProvider:update',
      'identityProvider:delete',
      'group:create',
      'group:read',
      'group:update',
      'group:delete',
      'group:assignRole',
      'group:export',
      'authz:explain',
      'serviceAccount:create',
      'serviceAccount:read',
      'serviceAccount:update',
      'serviceAccount:delete',
      'serviceAccount:export',
      'webhook:create',
      'webhook:read',
      'webhook:update',
      'webhook:delete',
      'tag:create',
      'tag:update',
      'tag:delete',
      'tag:export',
      'notification:read',
      'announcement:create',
      'announcement:read',
      'announcement:update',
      'announcement:delete',
      'announcement:publish',
      'mfaPolicy:read',
      'orgUnit:create',
      'orgUnit:read',
      'orgUnit:update',
      'orgUnit:delete',
      'orgUnit:export',
      'approval:override',
      'approvalFlow:read',
      'approvalFlow:update',
      'comment:delete',
    ],
  },
  {
    slug: 'auditor',
    name: '稽核人員',
    description: '唯讀存取使用者、角色、群組、外部 IdP 連線與稽核日誌。',
    isSystem: true,
    permissions: [
      'user:read',
      'role:read',
      'permission:read',
      'auditLog:read',
      'auditLog:export',
      'system:read',
      'approval:read',
      'approval:export',
      'file:read',
      'job:read',
      'identityProvider:read',
      'group:read',
      'authz:explain',
      'serviceAccount:read',
      'webhook:read',
      'announcement:read',
      'mfaPolicy:read',
      'orgUnit:read',
      'approvalFlow:read',
    ],
  },
  {
    slug: 'member',
    name: '一般成員',
    description: '個人頁面，以及被授權的資料夾。未來功能的權限掛載點。',
    isSystem: true,
    // 進得了檔案管理器；範圍由資料夾授權決定（docs/architecture/iam/06-resource-grants.md）
    permissions: ['file:access'],
  },
] as const;
