/**
 * 後端錯誤碼 → 語系鍵。key 以完整字面量寫在表裡，不以 `` `error.${code}` `` 組字串
 * （docs/conventions/06-literal-strings.md §3.1）。
 *
 * 錯誤碼的來源是後端 `apps/api/src/core/errors/error-code.ts`；新增錯誤碼時同步加在這裡
 * 與兩個語系檔的 `error.<CODE>`（`app/__tests__/locales.test.ts` 會比對）。
 */
export const ERROR_MESSAGE_KEY = {
  // ── 驗證 ──
  VALIDATION_FAILED: 'error.VALIDATION_FAILED',

  // ── 租戶 ──
  TENANT_NOT_FOUND: 'error.TENANT_NOT_FOUND',
  TENANT_UNAVAILABLE: 'error.TENANT_UNAVAILABLE',
  FEATURE_DISABLED: 'error.FEATURE_DISABLED',
  FEATURE_FLAG_NOT_FOUND: 'error.FEATURE_FLAG_NOT_FOUND',
  PLATFORM_ONLY: 'error.PLATFORM_ONLY',
  TENANT_CODE_TAKEN: 'error.TENANT_CODE_TAKEN',
  TENANT_DOMAIN_TAKEN: 'error.TENANT_DOMAIN_TAKEN',
  TENANT_STATUS_CONFLICT: 'error.TENANT_STATUS_CONFLICT',
  TENANT_LAST_DOMAIN: 'error.TENANT_LAST_DOMAIN',
  TENANT_PRIMARY_DOMAIN: 'error.TENANT_PRIMARY_DOMAIN',
  PLATFORM_ADMIN_NOT_FOUND: 'error.PLATFORM_ADMIN_NOT_FOUND',

  // ── 認證 ──
  AUTH_INVALID_CREDENTIALS: 'error.AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_PENDING: 'error.AUTH_ACCOUNT_PENDING',
  AUTH_ACCOUNT_DISABLED: 'error.AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED: 'error.AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_INVALID: 'error.AUTH_TOKEN_INVALID',
  AUTH_TOKEN_STALE: 'error.AUTH_TOKEN_STALE',
  AUTH_API_TOKEN_EXPIRED: 'error.AUTH_API_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'error.AUTH_REFRESH_INVALID',
  AUTH_REFRESH_EXPIRED: 'error.AUTH_REFRESH_EXPIRED',
  AUTH_REFRESH_REVOKED: 'error.AUTH_REFRESH_REVOKED',
  AUTH_REFRESH_REUSED: 'error.AUTH_REFRESH_REUSED',
  AUTH_PASSWORD_MISMATCH: 'error.AUTH_PASSWORD_MISMATCH',
  AUTH_PASSWORD_WEAK: 'error.AUTH_PASSWORD_WEAK',
  AUTH_SETUP_TOKEN_INVALID: 'error.AUTH_SETUP_TOKEN_INVALID',
  AUTH_REGISTRATION_DISABLED: 'error.AUTH_REGISTRATION_DISABLED',
  AUTH_SSO_INTERACTION_INVALID: 'error.AUTH_SSO_INTERACTION_INVALID',
  AUTH_SSO_CODE_INVALID: 'error.AUTH_SSO_CODE_INVALID',
  AUTH_SSO_REQUIRED: 'error.AUTH_SSO_REQUIRED',
  AUTH_SSO_ACCOUNT_NOT_FOUND: 'error.AUTH_SSO_ACCOUNT_NOT_FOUND',
  AUTH_SSO_LINK_NOT_ALLOWED: 'error.AUTH_SSO_LINK_NOT_ALLOWED',
  AUTH_SSO_PROVIDER_UNAVAILABLE: 'error.AUTH_SSO_PROVIDER_UNAVAILABLE',
  AUTH_SSO_EXTERNAL_FAILED: 'error.AUTH_SSO_EXTERNAL_FAILED',

  // ── 授權 ──
  AUTHZ_FORBIDDEN: 'error.AUTHZ_FORBIDDEN',
  AUTHZ_ESCALATION: 'error.AUTHZ_ESCALATION',
  AUTHZ_SELF_MODIFY: 'error.AUTHZ_SELF_MODIFY',
  ROUTE_PERMISSION_NOT_DECLARED: 'error.ROUTE_PERMISSION_NOT_DECLARED',

  // ── 使用者 ──
  USER_NOT_FOUND: 'error.USER_NOT_FOUND',
  USER_EMAIL_DUPLICATE: 'error.USER_EMAIL_DUPLICATE',
  USER_USERNAME_DUPLICATE: 'error.USER_USERNAME_DUPLICATE',
  USER_NOT_LOCKED: 'error.USER_NOT_LOCKED',
  USER_NOT_DELETED: 'error.USER_NOT_DELETED',
  USER_ROLES_CONFLICT: 'error.USER_ROLES_CONFLICT',
  USER_VERSION_CONFLICT: 'error.USER_VERSION_CONFLICT',

  // ── 角色 ──
  ROLE_NOT_FOUND: 'error.ROLE_NOT_FOUND',
  ROLE_NAME_DUPLICATE: 'error.ROLE_NAME_DUPLICATE',
  ROLE_SYSTEM_PROTECTED: 'error.ROLE_SYSTEM_PROTECTED',
  ROLE_SUPER_ADMIN_IMMUTABLE: 'error.ROLE_SUPER_ADMIN_IMMUTABLE',
  ROLE_IN_USE: 'error.ROLE_IN_USE',
  LAST_SUPER_ADMIN: 'error.LAST_SUPER_ADMIN',
  ROLE_SELF_LOCKOUT: 'error.ROLE_SELF_LOCKOUT',
  ROLE_VERSION_CONFLICT: 'error.ROLE_VERSION_CONFLICT',
  ROLE_NOT_DELETED: 'error.ROLE_NOT_DELETED',
  GROUP_NOT_FOUND: 'error.GROUP_NOT_FOUND',
  GROUP_NAME_DUPLICATE: 'error.GROUP_NAME_DUPLICATE',
  GROUP_VERSION_CONFLICT: 'error.GROUP_VERSION_CONFLICT',
  GROUP_NOT_DELETED: 'error.GROUP_NOT_DELETED',
  GROUP_MEMBERSHIP_CYCLE: 'error.GROUP_MEMBERSHIP_CYCLE',
  GROUP_NESTING_TOO_DEEP: 'error.GROUP_NESTING_TOO_DEEP',
  GROUP_SUPER_ADMIN_FORBIDDEN: 'error.GROUP_SUPER_ADMIN_FORBIDDEN',
  SERVICE_ACCOUNT_NOT_FOUND: 'error.SERVICE_ACCOUNT_NOT_FOUND',
  SERVICE_ACCOUNT_VERSION_CONFLICT: 'error.SERVICE_ACCOUNT_VERSION_CONFLICT',
  SERVICE_ACCOUNT_ROLES_CONFLICT: 'error.SERVICE_ACCOUNT_ROLES_CONFLICT',
  API_TOKEN_NOT_FOUND: 'error.API_TOKEN_NOT_FOUND',
  API_TOKEN_LIFETIME_EXCEEDED: 'error.API_TOKEN_LIFETIME_EXCEEDED',
  API_TOKEN_LIMIT_REACHED: 'error.API_TOKEN_LIMIT_REACHED',
  WEBHOOK_NOT_FOUND: 'error.WEBHOOK_NOT_FOUND',
  WEBHOOK_VERSION_CONFLICT: 'error.WEBHOOK_VERSION_CONFLICT',
  WEBHOOK_URL_NOT_ALLOWED: 'error.WEBHOOK_URL_NOT_ALLOWED',
  WEBHOOK_EVENT_UNKNOWN: 'error.WEBHOOK_EVENT_UNKNOWN',
  WEBHOOK_DISABLED: 'error.WEBHOOK_DISABLED',
  WEBHOOK_LIMIT_REACHED: 'error.WEBHOOK_LIMIT_REACHED',
  WEBHOOK_URL_LIMIT_REACHED: 'error.WEBHOOK_URL_LIMIT_REACHED',
  WEBHOOK_DELIVERY_NOT_FOUND: 'error.WEBHOOK_DELIVERY_NOT_FOUND',
  ANNOUNCEMENT_NOT_FOUND: 'error.ANNOUNCEMENT_NOT_FOUND',
  ANNOUNCEMENT_VERSION_CONFLICT: 'error.ANNOUNCEMENT_VERSION_CONFLICT',
  ANNOUNCEMENT_INVALID_STATE: 'error.ANNOUNCEMENT_INVALID_STATE',
  ANNOUNCEMENT_TRIGGER_IN_PAST: 'error.ANNOUNCEMENT_TRIGGER_IN_PAST',
  ANNOUNCEMENT_AUDIENCE_EMPTY: 'error.ANNOUNCEMENT_AUDIENCE_EMPTY',
  ANNOUNCEMENT_EVENT_UNKNOWN: 'error.ANNOUNCEMENT_EVENT_UNKNOWN',
  ANNOUNCEMENT_NOT_DELETED: 'error.ANNOUNCEMENT_NOT_DELETED',
  ANNOUNCEMENT_DISPATCH_NOT_FOUND: 'error.ANNOUNCEMENT_DISPATCH_NOT_FOUND',
  ANNOUNCEMENT_DISPATCH_NOT_REVOCABLE: 'error.ANNOUNCEMENT_DISPATCH_NOT_REVOCABLE',
  ANNOUNCEMENT_MESSAGE_NOT_FOUND: 'error.ANNOUNCEMENT_MESSAGE_NOT_FOUND',
  TAG_NOT_FOUND: 'error.TAG_NOT_FOUND',
  TAG_VERSION_CONFLICT: 'error.TAG_VERSION_CONFLICT',
  TAG_NAME_DUPLICATE: 'error.TAG_NAME_DUPLICATE',
  TAG_SCOPE_NOT_FOUND: 'error.TAG_SCOPE_NOT_FOUND',
  TAG_LIMIT_REACHED: 'error.TAG_LIMIT_REACHED',
  REVISION_NOT_FOUND: 'error.REVISION_NOT_FOUND',
  REVISION_UNAVAILABLE: 'error.REVISION_UNAVAILABLE',
  NOTIFICATION_NOT_FOUND: 'error.NOTIFICATION_NOT_FOUND',
  NOTIFICATION_EVENT_NOT_FOUND: 'error.NOTIFICATION_EVENT_NOT_FOUND',
  NOTIFICATION_EVENT_MANDATORY: 'error.NOTIFICATION_EVENT_MANDATORY',
  NOTIFICATION_PREFERENCE_LOCKED: 'error.NOTIFICATION_PREFERENCE_LOCKED',

  // ── 權限 ──
  PERMISSION_UNKNOWN: 'error.PERMISSION_UNKNOWN',

  // ── 審批 ──
  APPROVAL_NOT_FOUND: 'error.APPROVAL_NOT_FOUND',
  APPROVAL_ALREADY_REVIEWED: 'error.APPROVAL_ALREADY_REVIEWED',
  APPROVAL_SELF_REVIEW: 'error.APPROVAL_SELF_REVIEW',

  // ── 外部 IdP 連線 ──
  IDENTITY_PROVIDER_NOT_FOUND: 'error.IDENTITY_PROVIDER_NOT_FOUND',
  IDENTITY_PROVIDER_NAME_DUPLICATE: 'error.IDENTITY_PROVIDER_NAME_DUPLICATE',
  IDENTITY_PROVIDER_DOMAIN_TAKEN: 'error.IDENTITY_PROVIDER_DOMAIN_TAKEN',
  IDENTITY_PROVIDER_LIMIT_REACHED: 'error.IDENTITY_PROVIDER_LIMIT_REACHED',

  // ── 背景工作 ──
  JOB_NOT_FOUND: 'error.JOB_NOT_FOUND',
  JOB_NOT_RETRYABLE: 'error.JOB_NOT_RETRYABLE',

  // ── 檔案 ──
  FILE_NOT_FOUND: 'error.FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'error.FILE_TOO_LARGE',
  FILE_STORAGE_QUOTA_EXCEEDED: 'error.FILE_STORAGE_QUOTA_EXCEEDED',
  FILE_ALREADY_UPLOADED: 'error.FILE_ALREADY_UPLOADED',
  FILE_UPLOAD_INCOMPLETE: 'error.FILE_UPLOAD_INCOMPLETE',
  FILE_SIZE_MISMATCH: 'error.FILE_SIZE_MISMATCH',
  FILE_STORAGE_UNAVAILABLE: 'error.FILE_STORAGE_UNAVAILABLE',
  FILE_UPLOAD_PART_INVALID: 'error.FILE_UPLOAD_PART_INVALID',
  FILE_VERSION_CONFLICT: 'error.FILE_VERSION_CONFLICT',
  FILE_IMAGE_URL_INVALID: 'error.FILE_IMAGE_URL_INVALID',
  FILE_FOLDER_NOT_FOUND: 'error.FILE_FOLDER_NOT_FOUND',
  FILE_FOLDER_NAME_CONFLICT: 'error.FILE_FOLDER_NAME_CONFLICT',
  FILE_FOLDER_CYCLE: 'error.FILE_FOLDER_CYCLE',
  FILE_FOLDER_SYSTEM_PROTECTED: 'error.FILE_FOLDER_SYSTEM_PROTECTED',
  FILE_NOT_DELETED: 'error.FILE_NOT_DELETED',
  FILE_RESTORE_CONFLICT: 'error.FILE_RESTORE_CONFLICT',
  FILE_FOLDER_NOT_DELETED: 'error.FILE_FOLDER_NOT_DELETED',
  FILE_FOLDER_RESTORE_CONFLICT: 'error.FILE_FOLDER_RESTORE_CONFLICT',
  FILE_GRANT_SUBJECT_NOT_FOUND: 'error.FILE_GRANT_SUBJECT_NOT_FOUND',
  FILE_GRANT_NOT_FOUND: 'error.FILE_GRANT_NOT_FOUND',
  FILE_ACCESS_ALREADY_GRANTED: 'error.FILE_ACCESS_ALREADY_GRANTED',
  FILE_ACCESS_REQUEST_NOT_FOUND: 'error.FILE_ACCESS_REQUEST_NOT_FOUND',

  // ── 通用 ──
  SETTING_NOT_FOUND: 'error.SETTING_NOT_FOUND',
  NOT_FOUND: 'error.NOT_FOUND',
  CONFLICT: 'error.CONFLICT',
  RATE_LIMITED: 'error.RATE_LIMITED',
  INTERNAL_ERROR: 'error.INTERNAL_ERROR',
} as const;

/** 前端認得的後端錯誤碼。 */
export type KnownErrorCode = keyof typeof ERROR_MESSAGE_KEY;

/** 取得錯誤碼對應的語系鍵；不認得的碼回 `undefined`（由呼叫端退回通用訊息）。 */
export function getErrorMessageKey(code: string): string | undefined {
  return Object.hasOwn(ERROR_MESSAGE_KEY, code)
    ? ERROR_MESSAGE_KEY[code as KnownErrorCode]
    : undefined;
}
